email:
  from: "portus@example.com"
  name: "Portus"
  reply_to: "no-reply@example.com"
  smtp:
    enabled: false
    address: "smtp.example.com"
    port: 587,
    user_name: "username@example.com"
    password: "password"
    domain: "example.com"
gravatar:
  enabled: true
delete:
  enabled: XXX-PORTUS_DELETE_ENABLED-XXX
ldap:
  enabled: false
  hostname: "ldap_hostname"
  port: 389
  method: "plain"
  base: ""
  filter: ""
  uid: "uid"
  authentication:
    enabled: false
    bind_dn: ""
    password: ""
  guess_email:
    enabled: false
    attr: ""
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: XXX-PORTUS_CHECK_SSL_USAGE_ENABLED-XXX
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
machine_fqdn:
  value: XXX-PORTUS_MACHINE_FQDN-XXX
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  manage_team:
    enabled: true
  manage_namespace:
    enabled: true
