default: &default
  secret_key_base: 8bc8ccc710eafd73d43cd59ac8881aadc89f7a6ab55f1ac11c97fb436a3931cc78c38e735e664958d9e793725f3d52178f4e2c3
  encryption_private_key_path: '/certs/server.key'
  machine_fqdn: '127.0.0.1'
  portus_password: 'portus1234'

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
