default: &default
  secret_key_base: XXX-PORTUS_SECRET_KEY_BASE-XXX
  encryption_private_key_path: 'XXX-PORTUS_ENCRYPTION_PRIVATE_KEY_PATH-XXX'
  portus_password: 'XXX-PORTUS_PORTUS_PASSWORD-XXX'

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
